#
# Card de Login 
<LoginCard@MDCard>:
    md_bg_color: [230/255, 225/255, 219/255,   1]
    size_hint: 0, 0 
    pos_hint: {'center_x': 0.50, 'center_y': 0.50 }
    orientation: 'vertical' 
    elevation: 2
    MDBoxLayout:
        size_hint: 1, 0.2 
        padding: [ 25, 0, 25, 0]
        orientation: 'horizontal'
        MDLabel: 
            size_hint_x: 0.9
            text: 'Login'
            color:  [203/255,  95/255,  65/255,   1]
            font_size: 16
        MDIconButton:
            size_hint_x: 0.1
            icon: 'close'
            pos_hint: {'right': 1, 'center_y': .5 }
            theme_text_color: 'Custom'
            text_color: 203/255,  95/255,  65/255,   1
            on_release: root.parent.controller.close_login()
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 0.9, 0.8 
        pos_hint: {'center_x': .5 }
        MDTextField:
            id: user 
            hint_text: 'Usuário:'
            pos_hint: {'center_x': .5 }
            max_text_length: 32
            hint_text: 'Usuário'
            icon_left: 'account-circle'
            icon_left_color_focus:  203/255,  95/255,  65/255,   1
            line_color_focus: 203/255,  95/255,  65/255,   1
            text_color_focus:  203/255,  95/255,  65/255,   1
            hint_text_color_focus:  203/255,  95/255,  65/255,   1
            mode: "rectangle"  
        MDBoxLayout:
            orientation: 'horizontal'
            pos_hint: {'center_x': .5 }
            MDTextField:
                id: password
                hint_text: 'Senha'
                password: True 
                mode: "rectangle"
                helper_text: 'Nunca compartilhe sua senha.'
                pos_hint: {'center_x': .5 }
                icon_left: 'key-variant'
                icon_left_color_focus:  203/255,  95/255,  65/255,   1
                line_color_focus: 203/255,  95/255,  65/255,   1
                text_color_focus:  203/255,  95/255,  65/255,   1
                hint_text_color_focus:  203/255,  95/255,  65/255,   1
            MDIconButton:
                icon: "eye-off"
                pos_hint: {"right": .95}
                theme_icon_color: 'Custom'
                icon_color:  203/255,  95/255,  65/255,   1
                on_release:
                    self.icon = "eye" if self.icon == "eye-off" else "eye-off"
                    password.password = False if password.password is True else True
        MDLabel:
#
# Card de registro
<RegisterCard@MDCard>:
    md_bg_color: [230/255, 225/255, 219/255,   1]
    size_hint: 0, 0 
    pos_hint: {'center_x': 0.50, 'center_y': 0.50 }
    orientation: 'vertical' 
    elevation: 2
    MDBoxLayout:
        size_hint: 1, 0.2 
        padding: [ 25, 0, 25, 0]
        orientation: 'horizontal'
        MDLabel: 
            size_hint_x: 0.9
            text: 'Registrar novo usuário'
            color:  [203/255,  95/255,  65/255,   1]
            font_size: 16
        MDIconButton:
            size_hint_x: 0.1
            icon: 'close'
            pos_hint: {'right': 1, 'center_y': .5 }
            theme_text_color: 'Custom'
            text_color: 203/255,  95/255,  65/255,   1
            on_release: root.parent.controller.close_register()
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 0.9, 0.8 
        pos_hint: {'center_x': .5 }
        #
        # Text fields
        MDTextField:
            id: user 
            hint_text: 'Nome de usuário:'
            pos_hint: {'center_x': .5 }
            size_hint_y: 0.2
            max_text_length: 32
            icon_left: 'account-circle'
            icon_left_color_focus:  203/255,  95/255,  65/255,   1
            line_color_focus: 203/255,  95/255,  65/255,   1
            text_color_focus:  203/255,  95/255,  65/255,   1
            hint_text_color_focus:  203/255,  95/255,  65/255,   1
            mode: "rectangle"  
        MDBoxLayout:
            orientation: 'horizontal'
            pos_hint: {'center_x': .5, 'center_y': 0.5 }
            size_hint_y: 0.2
            MDTextField:
                id: password
                hint_text: 'Senha:'
                password: True 
                mode: "rectangle"
                pos_hint: {'center_x': .5 }
                icon_left: 'key-variant'
                icon_left_color_focus:  203/255,  95/255,  65/255,   1
                line_color_focus: 203/255,  95/255,  65/255,   1
                text_color_focus:  203/255,  95/255,  65/255,   1
                hint_text_color_focus:  203/255,  95/255,  65/255,   1
            MDIconButton:
                icon: "eye-off"
                pos_hint: {"right": .95}
                theme_icon_color: 'Custom'
                icon_color:  203/255,  95/255,  65/255,   1
                on_release:
                    self.icon = "eye" if self.icon == "eye-off" else "eye-off"
                    password.password = False if password.password is True else True
        MDTextField:
            id: pet_name 
            size_hint_y: 0.2
            hint_text: 'Nome do pet:'
            pos_hint: {'center_x': .5 }
            max_text_length: 32
            icon_left: 'cat'
            icon_left_color_focus:  203/255,  95/255,  65/255,   1
            line_color_focus: 203/255,  95/255,  65/255,   1
            text_color_focus:  203/255,  95/255,  65/255,   1
            hint_text_color_focus:  203/255,  95/255,  65/255,   1
            mode: "rectangle" 
        MDTextField:
            id: pet_age 
            size_hint_y: 0.2
            hint_text: 'Idade do pet:'
            pos_hint: {'center_x': .5 }
            max_text_length: 32
            icon_left:'view-agenda-outline'
            icon_left_color_focus:  203/255,  95/255,  65/255,   1
            line_color_focus: 203/255,  95/255,  65/255,   1
            text_color_focus:  203/255,  95/255,  65/255,   1
            hint_text_color_focus:  203/255,  95/255,  65/255,   1
            mode: "rectangle" 
        MDLabel:
            size_hint_y: 0.2
            

<LoginScreenView>
    md_bg_color: [230/255, 225/255, 219/255,   1]

    # Title 
    MDFloatLayout:
        size_hint: 1, 0.2
        pos_hint: {'center_x': 0.5,'top': 1 }
        MDLabel:
            pos_hint: {'center_x': 0.5,'top': 0.9 }
            size_hint: 0.5, 0.5
            text: "[b]Cat[/b] Bed"
            color: [203/255,  95/255,  65/255,   1]
            font_style: 'H3'
            markup: True
            halign: 'center' 
            valign: 'bottom'
    
    # Logo 
    MDFloatLayout:
        size_hint: 0.7, 0.3
        pos_hint: {'center_x': 0.5,'top': 0.9 }
        AsyncImage:
            pos_hint: {'center_x': 0.55,'top': 1 }
            size_hint: None, None
            size: self.texture_size
            source: root.model.logo
            allow_stretch: True
    
    # Login card 
    MDFloatLayout:
        size_hint: 0.5, 0.4
        pos_hint: {'center_x': 0.50, 'top': 0.5}
        MDRoundFlatIconButton:
            id: button_login 
            pos_hint: {'center_x': 0.50,'top': 1}
            size_hint: 1, 0.15
            text: "LOGIN"
            font_style: 'Subtitle2'
            icon: "cat"
            theme_icon_color: 'Custom' 
            icon_color:  [230/255, 225/255, 219/255,   1]       
            text_color:  [230/255, 225/255, 219/255,   1]
            md_bg_color: [203/255,  95/255,  65/255,   1]
            line_color:  'white'
            
    # Register card
    MDFloatLayout:
        size_hint: 0.75, 0.1            
        pos_hint: {'center_x': 0.50, 'top': 0.15}
        MDRoundFlatIconButton:
            id: button_register
            pos_hint: {'center_x': 0.50,'top': 1}
            size_hint: 1, 0.6
            text: "REGISTRO"
            font_style: 'Subtitle2'
            icon:'pen-plus'
            theme_icon_color: 'Custom' 
            icon_color:  [230/255, 225/255, 219/255,   1]       
            text_color:  [230/255, 225/255, 219/255,   1]
            md_bg_color: [203/255,  95/255,  65/255,   1]
            line_color:  'white'